class CommonLog:
    SUCCESS = "success"
    ADDRESS_CREATE_REQUEST = "Received create address request"
    ADDRESS_UPDATE_REQUEST = "Received update address request for id={id}"
    ADDRESS_DELETE_REQUEST = "Received delete address request for id={id}"
    ADDRESS_GET_REQUEST = "Received get address request for id={id}"
    ADDRESS_LIST_REQUEST = "Received list addresses request"
    ADDRESS_LIST_NEARBY_REQUEST = "Received list addresses within radius request"
    ADDRESS_CREATED = "Address created successfully"
    ADDRESS_UPDATED = "Address updated successfully"
    ADDRESS_DELETED = "Address deleted successfully"
    ADDRESS_NOT_FOUND = "Address not found"
    INTERNAL_SERVER_ERROR = "Internal Server Error"
    UNEXPECTED_ERROR_FOR_ENDPOINT = "Unexpected Error Occurred: {method} {path}"
    LIST_WITHIN_RADIUS_FAILED = "Failed to list addresses within radius: {error}"
